### ISSUE TITLE
[Overwatch] Corsair R65Keyboard doesn't work

### ISSUE THREAD

**Issue by Cerea1127** [SpoinkyNL/Artemis#140]
Hey mate amazing stuff here, just want to get things working.

i've installed everything and located the game just fine.

the debugger works and i can see the debugger interacting with the game but my actual keyboard does not light up. 

any ideas on how i can get things working? Cheers mate.

**Comment by SpoinkyNL** [comment]
Hey, Cerea!

I'm sorry you're having trouble getting it working. Could you set the logging mode to debug, restart Artemis and try to rerun the game?

I don't have the K65 myself so it might be identifying itself with a name Artemis doesn't recognize, in which case it'll be an easy fix for me :+1:

**Comment by Cerea1127** [comment]
Thanks for the quick reply SpoinkyNL.
Changed the log level to debug but nothing yet.
If its anything to note, it still shows the "to get started, please set up a keyboard in the settings menu and enable this effect / game" on the preview.

Thanks again.

**Comment by SpoinkyNL** [comment]
Hey,

Could you head over to Documents > Artemis > logs and post the log file
that's in there?

Thanks!

Op 15 aug. 2016 02:50 schreef "Cerea1127" <notifications@github.com>:

Thanks for the quick reply SpoinkyNL.
Changed the log level to debug but nothing yet.
If its anything to note, it still shows the "to get started, please set up
a keyboard in the settings menu and enable this effect / game" on the
preview.

Thanks again.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/SpoinkyNL/Artemis/issues/140#issuecomment-239710178>,
or mute the thread

**Comment by Cerea1127** [comment]
[2016-08-15.txt](https://github.com/SpoinkyNL/Artemis/files/418015/2016-08-15.txt)

I believe this is what you're looking for!

**Comment by SpoinkyNL** [comment]
Yup, that's the one :+1: 

I've added the CGK65 RGB as a variant of the K65. I'm not at some atm so I can't give you a new release but I'll upload one tonight :)

**Comment by Cerea1127** [comment]
thank you very much! eagerly awaiting to test it out!

**Comment by SpoinkyNL** [comment]
https://github.com/SpoinkyNL/Artemis/releases/tag/1.2.3.1 There you go :)

**Comment by Cerea1127** [comment]
Thank you it works! awesome stuff!

**Comment by SpoinkyNL** [comment]
Ok great :) I'm closing this issue then, should you run into any trouble feel free to make a new one!
