### ISSUE TITLE
QWERTZ keyboard layout

### ISSUE THREAD

**Issue by Chris92de** [SpoinkyNL/Artemis#185]
Hey there, currently I only see support for QWERTY and AZERTY layouts in Artemis... 
Can QWERTZ users get some love too please? <3

**Comment by SpoinkyNL** [comment]
Hey, could post a clear top-down picture of your keyboard?

**Comment by DarthAffe** [comment]
I'm using a QWERTZ-keyboard (german-layout).
If you give me a hint on what to do I could add this.

**Comment by Chris92de** [comment]
[Here's the best image I could find](https://images-na.ssl-images-amazon.com/images/I/81qYT9Q7cIL._SL1500_.jpg)

**Comment by SpoinkyNL** [comment]
Thanks for the image, works for me :)

@DarthAffe because CUE.NET is the only SDK that can resolve keys into positions, for the other keyboards I've had to create these [key maps](https://github.com/SpoinkyNL/Artemis/blob/master/Artemis/Artemis/DeviceProviders/Logitech/Utilities/KeyMap.cs) for each layout. 

They aren't extremely accurate but it's only used by the KeyPress effect and LUA anyways. If you're bored you could create one for QWERTZ but it's a pain in the ass, if you cba I'll do it before release :p

**Comment by DarthAffe** [comment]
I'll create the mapping for the QWERTZ-Layout, but I can't test it, if it only works with non-corsair-keyboards :(

> Oh for CUE I had to write this and this to resolve a regular WinForms key to a CueKey, might be nice to clean up and include in CUE.NET

Yes, that seems to be useful - I'll look into it.

**Comment by SpoinkyNL** [comment]
That's great, @Chris92de can perhaps give feedback on it when I put it live. I'm pretty much ready for an update, just ironing out some UI stuff (and I'll wait on the QWERTZ map :) )

**Comment by SpoinkyNL** [comment]
Update with QWERTZ map pushed, lemme know how it works

**Comment by SpoinkyNL** [comment]
I'll assume this is fine now
