### ISSUE TITLE
Custom Games/Programms or new Effect Conditions 

### ISSUE THREAD

**Issue by MikeUNtested** [SpoinkyNL/Artemis#219]
Hello, nice work.
I have the request to select own Programms and games so I can make more specific profiles.
The same could be archieved when as effect condition, programms could be  selected.

I want to use the MusicVirtuallizer only when my music player Winamp is in focus.
Use the ambilight in chrome,vlc and other specific games.
Use the gif profil in other specific programms. etc.

I really hope you can implement this, none of the other 3party Corsair api programms has so good functions like this programm.

**Comment by DarthAffe** [comment]
@SpoinkyNL If you don't mind I'd go for that. I think I've quite a solid idea on how to implement this :p

**Comment by SpoinkyNL** [comment]
@DarthAffe yeah cool, go ahead :D

**Comment by DarthAffe** [comment]
yeah :) I'll go for it this weekend. Just one more question in advance.
Hooking into the event to get notified if the currently active window changes and obtaining the process to that window (that's what we need to do here), might trigger heuristics of some avs. How should we handle this?
We could make this feature a special 'op-in'-thing, so that we are able to explicit point that problem out when someone is going to use it. Of course we could also just add it and hope for the best to make it somehow easier to use.

**Comment by SpoinkyNL** [comment]
Artemis currently already logs all your key presses for the keypress layer type and it hasn't triggered  any false positives AFAIK. So hopefully this won't either. Otherwise I might look into signing the application, this awards a lot of trust points, or so I've read.

**Comment by SpoinkyNL** [comment]
This is added to Artemis in 1.7.0.0 :) 

Thanks @DarthAffe!
