### ISSUE TITLE
(CS:GO) Game Profile re-activates itself after reboot; Artemis crashes when trying to remove the game path.

### ISSUE THREAD

**Issue by vaaski** [SpoinkyNL/Artemis#269]
Hello! First of I'd really like to thank you for this amazing piece of software.  I've donated 5€, which was the first time I have ever contributed to development voluntarily. I hope this helps at least a little bit :)

Here comes the useful stuff:
Because I like to use the default LGS CS:GO integration, I've toggled the Artemis one off (after trying it of course). But after a reboot or even a restart of Artemis it switched back on. So another method would be to simply remove the path of CS:GO in Artemis. But that crashed it with [this](http://pastebin.com/9KKN8yvk) error.

Except for those two things Artemis seems to be flawless.
A feature that I'd like to see is to change the accent color of the whole program, but that would be just for aesthetics.

**Comment by SpoinkyNL** [comment]
Hey, thanks for the kind donation, appreciate it! 

As for the issue you described, I think I've fixed it already for the next release because I've given the code that handles enabling/disabling games a major haul over. So I might've fixed this without knowing it was an issue but I'll be sure to give CS some extra attention :)

**Comment by SpoinkyNL** [comment]
Hey, please let me know how this goes in the latest release ^^

**Comment by vaaski** [comment]
Sorry for the late answer, wasn't home in a couple of days.
It works flawless now! Thank you so much :)

**Comment by SpoinkyNL** [comment]
Great, ty for reporting back!
