### ISSUE TITLE
Logo redesign submission

### ISSUE THREAD

**Issue by vaaski** [SpoinkyNL/Artemis#270]
Right after I've submitted #269, I thought of other ways I could contribute to development.
Don't get me wrong - the current logo is fine, but I think there is way for improvements.
I played around a while and came up with something like this.

![logoteal](https://cloud.githubusercontent.com/assets/17879327/21756490/3d4783da-d622-11e6-98c2-d916bef9fe94.png)

It's supposed to mimic a keycap, but a standalone version of the "A" wouldn't be a problem either.
Please tell me what you think! If you like this and want to work some more with me, I'd be happy to help wherever I can. Please consider [Emailing](mailto:admin@vaa.ski) me for further contact :)

**Comment by SpoinkyNL** [comment]
Hey, I like the idea of having a keycap but the bow is kind of important because of the name Artemis. It's the mythical archer that accidentally shot Orion and raised him to live along the stars. 

So I was wondering how it would look without the circle and the A replaced with the bow.

That would leave you with a white rounded square and the bow, which maybe doesn't emphasize it being a keycap, so how would some extra shading look, like on these? http://i.imgur.com/M1JPfc2.png

I realize that way we lose the flat look but it might work

**Comment by Arttumiro** [comment]
I think it would be nice to have a choice between like 2 or more icons. Because i really like Vaaski's keycap design.
