### ISSUE TITLE
Get ambilight colour through lua/c#

### ISSUE THREAD

**Issue by MikeUNtested** [SpoinkyNL/Artemis#310]
Is there a way to get the average color from the ambilight layer and send it to a serial port/arduino?

I'm not able to find how i could implement it myself in your programm with c# or with a lua script.

**Comment by SpoinkyNL** [comment]
Would be nice since that way the layer can support multiple device types through LUA.
@DarthAffe how feasible is this?

**Comment by DarthAffe** [comment]
Hmm, I'd say right now this isn't possible. You'd have to calculate the colors in lua and as far as i know it's not possible to get colors there.
Also you might not be able to send the data to a serial port since the necessary libraries aren't loaded.

**Comment by SpoinkyNL** [comment]
Alright, was mainly thinking about a property on the layer that could be accessed from LUA.

So you could simply do something like:
```lua
local layer = Profile.GetLayerByName("Ambient layer");
local color = layer.AmbientAverage;
```

@MikeUNtested you indeed cannot access your Arduino from LUA. In C# it's trivial however. To implement your own device see this guide:  https://github.com/SpoinkyNL/Artemis/wiki/Adding-a-non-keyboard-device-yourself

**Comment by DarthAffe** [comment]
Sure, such a property could be added, but I don't see a real (generic) benefit which would justify the performance impact for the majority of the users.

Since MikeUNtested has to implement a own device anyway to cover his specific case, he can just average the bitmap on update and gets exactly what he wants.

**Comment by SpoinkyNL** [comment]
I was thinking along the lines of allowing all devices access to average screen color, since the current Ambient layer is a keyboard layer other devices cannot display it. However, I forgot this would mean having to keep the screen capture active all the time and it's not worth the performance loss.


@MikeUNtested This leaves you with the option of implementing your own generic device and creating a new _Generic device layer type_ based on [AmbientLightType.cs](https://github.com/SpoinkyNL/Artemis/blob/f9b753f878a1ea116bdad850ad233033c332326c/Artemis/Artemis/Profiles/Layers/Types/AmbientLight/AmbientLightType.cs) and [GenericType.cs](https://github.com/SpoinkyNL/Artemis/blob/f9b753f878a1ea116bdad850ad233033c332326c/Artemis/Artemis/Profiles/Layers/Types/Generic/GenericType.cs)

This does go quite deep into Artemis's inner working though..

**Comment by MikeUNtested** [comment]
Ok, tkanks for your help.
I will try to implement my own device when I have time

**Comment by MikeUNtested** [comment]
At the start I tried to make the new generic device so simple it can get.
@SpoinkyNL , I tried to use your arduino sample to just give out the middle colour from the bitmap as single light. Do I have to recode/change something to activate Generic Devices?

I already did a red layer with Type "Generic (Logitech)" but it doens't seem to work.

```C#
using System;
using System.Drawing;
using System.IO.Ports;
using Ninject.Extensions.Logging;

namespace Artemis.DeviceProviders.ArduinoMega
{
    public class ArduinoMega : DeviceProvider
    {
        private SerialPort _port;

        public ArduinoMega(ILogger logger)
        {
            Logger = logger;
            Type = DeviceType.Generic;
        }

        public ILogger Logger { get; set; }

        public override void UpdateDevice(Bitmap bitmap)
        {
            if (bitmap == null)
                return;

            // If the device that's being implemented only has one LED, simply take the color 
            // of the pixel in the middle of the bitmap
            var color = bitmap.GetPixel(bitmap.Width / 2, bitmap.Height / 2);
            // Write the color to the device
            _port.Write("R");
            _port.Write(Convert.ToChar(color.R).ToString());
            _port.Write("G");
            _port.Write(Convert.ToChar(color.G).ToString());
            _port.Write("B");
            _port.Write(Convert.ToChar(color.B).ToString());
        }

        public override bool TryEnable()
        {
            var portNames = SerialPort.GetPortNames();
            try
            {
                _port = new SerialPort("Com3", 9600);
                _port.Open();
                /*
                foreach (var port in portNames)
                {
                    //Open serial port
                        if (_port.IsOpen)
                    {
                        CanUse = true;
                        break;
                    }
                }
               */
            }
            catch (Exception)
            {
                CanUse = false;
                Logger.Debug("Attempted to enable Arduino on Port '{0}'. CanUse: {1}", _port, CanUse);
            }

            return CanUse;
        }

        public override void Disable()
        {
            //port.Close();
            throw new NotSupportedException("Can only disable a keyboard");
        }
    }
}
```

**Comment by SpoinkyNL** [comment]
Hey, sorry for not getting back to you. I've been having some trouble finding spare time for Artemis.

If you set logging to Debug are you seeing the message ```Attempted to enable Arduino on Port 'x'. CanUse: True```?
