### ISSUE TITLE
Is the software 100% safe to use in overwatch?

### ISSUE THREAD

**Issue by Rabbitmxr** [SpoinkyNL/Artemis#314]

**Comment by SpoinkyNL** [comment]
Hey,

Artemis doesn't really touch Overwatch besides pretending to be the Razer API. So it doesn't inject anything into the game or act like cheating software etc. I've used it since day 1, even in competative and I've not been banned.

Of course I can't make any guarantees, if Blizzard decides to look out for Artemis and ban you for using it, they could do that but I don't see any reason why they would.
