### ISSUE TITLE
[Device Bug] [CM MasterKeys Pro L] Some keys on the numpad don't light up

### ISSUE THREAD

**Issue by KasperWadesluem** [SpoinkyNL/Artemis#328]
since the latest update, the numpad keys **9 6 3 , * -** as well as the **P3** and **P4** profile keys don't light up, **+** and **numpad enter** work normally though, so i don't think it's a scaling issue (?)

**Comment by Supermuskox** [comment]
+1 on this. Same keys aren't lighting up for me as well. Using the CM MasterKeys Pro L.

**Comment by manskou** [comment]
seems related to #327

On Mon, Mar 20, 2017, 12:55 PM Matthijs Boers <notifications@github.com>
wrote:

+1 on this. Same keys aren't lighting up for me as well. Using the CM
MasterKeys Pro L.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SpoinkyNL/Artemis/issues/328#issuecomment-287727837>,
or mute the thread

**Comment by SpoinkyNL** [comment]
Hey guys, I've noticed it too. It's an issue with the latest CM SDK (which is needed for mouse support).

I've messaged CM and they are looking into it. As soon as there's an SDK update I'll push a new version of Artemis to address this.

**Comment by jakehekesfists** [comment]
Has there been any update on this from CM Spoinky?
Anything we can do to help light a fire under them. (their software sucks compared to artemis)

**Comment by KasperWadesluem** [comment]
this issue has been fixed with the latest update, thanks :)
