### ISSUE TITLE
[Request] Add Roccat

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#369]
Roccat has a SDK so it should be easy to add. I see that someone made a github that does something similar. https://github.com/CosminLazar/roccat-talk-csharp

**Comment by LasseRosenow** [comment]
I see this is marked as completed, but I don't find a way to use my roccat keyboard with Artemis. Also no roccat device is listed under the supported devices.

What is the status of this? Is this really completed?

**Comment by diogotr7** [comment]
Hey, this issue was most likely closed when moving from Artemis 1 to 2 since that was a complete rewrite.

As for Roccat, that SDK mentioned does not support any of their recent products like the vulcan keyboards. There are some available options for Roccat, but since they're reverse engineered solutions and not officially supported by Roccat, we didn't include them as defaults. Check out:

* My plugin for Roccat [here](https://github.com/diogotr7/Artemis.Plugins.Devices.RoccatVulcan). It might need to be updated. If you want to try it out i can do so.
* OpenRGB [here](https://openrgb.org/) can be controlled by Artemis and might support your hardware.

**Comment by diogotr7** [comment]
I've updated the plugin, you should be able to use it when the build finishes running.

**Comment by agentwolf88** [comment]
Thank you for this plugin! I will test it tomorrow with a Vulkan TLK. I hope it works.

**Comment by agentwolf88** [comment]
Works fine. But the caps lock key does not work correctly. When i press this button the led is always on.
