### ISSUE TITLE
question about current time dynamic option

### ISSUE THREAD

**Issue by aureshion** [SpoinkyNL/Artemis#389]
How exactly can these be used? I would like to make some time based effects.

**Comment by rakosi2** [comment]
What I would do is make layers separate for each time and right click the layer/folder and in "Display if.." and change to "All met" click add condition. The first box Select "CurrentTime -> Hours24", select "Equal to" and in the third box the hour you want this layer/folder to display if you want it to be shown for that hour.
If you want to show between hours, instead of selecting "Equal to" I would make two conditions, one "Lower than" and one "Higher than".
![image](https://user-images.githubusercontent.com/6037087/30196707-94b376c0-9417-11e7-9206-7b068280c026.png)
