### ISSUE TITLE
[Library/Hardware Support] NZXT CAM (NZXT Kraken X61, etc) and ASUS AURA RGB

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#394]
What the title says. I would like to request some support for the NZXT Kraken X61 (as they previously removed "Smooth" transitioning between colors, so now it's on and off or just two colors switching instantly) so that it works in correspondence with the rest of my Audio Visualizer setup. If along that ASUS AURA RGB could be supported, that would be fantastic really (so that i can sync the entire RGB setup i have to just one software).

And Spoinky, i hope you are doing well, haven't seen or heard from you in a while.

Cheers, -Loke

**Comment by SpoinkyNL** [comment]
Hi hi, I definitely want to do some more devices like that. I'm rocking a Corsair Crystal 570x case which is full of LEDs which I want Artemis to control. It's tricky though because many of these devices don't have official APIs.

Thanks for the concern, I'm quite well but stupidly busy which my last year of uni and some other projects that took prio :\ I added a quick statement to the [readme](https://github.com/SpoinkyNL/Artemis/blob/master/README.md) :).

**Comment by DarthAffe** [comment]
I'll look into the ASUS AURA thing (using a mainboard with that stuff right now). There is a SDK now available but there isn't any documentation and the guys in the forum seems to be quite unhappy since it's quite a mess.
Anyway we'll need some help with keyboard, mouse and graphic cards - i've a asus-card but it isn't aura ready.

**Comment by therimmer96** [comment]
If you want to control the Hue+, you could look at this - https://github.com/kusti8/hue-plus

It has to replace CAM, but still.

**Comment by LokeYourLord** [comment]
@therimmer96 That's fantastic, that is Hue+ sorted out, just missing that it supports the Kraken Water Cooling series and then it should all be sorted out :D

**Comment by LokeYourLord** [comment]
Hmm, i dug a little deeper, maybe this could be to some help for you guys: https://github.com/jaksi/leviathan/blob/master/PROTOCOL.md

That is ONLY for the X61 however.

**Comment by SpoinkyNL** [comment]
That SDK should be pretty easy to wrap in C# if it's not done by someone already.
The first link you shared is pretty interesting, is there a sniffer that lets you check out what is being sent to USB devices?

**Comment by LokeYourLord** [comment]
@SpoinkyNL Yes there is such a thing, called USBPcap, found here: http://desowin.org/usbpcap/

**Comment by DarthAffe** [comment]
Just for the record: I'm already done with the asus thing (https://github.com/DarthAffe/RGB.NET/tree/master/RGB.NET.Devices.Aura), just looking in the forum for some guys to test all that stuff (there is absolutely no documentation for the sdk - that makes it even worse to use than the logitech one :p)

**Comment by LokeYourLord** [comment]
@DarthAffe I don't mind testing at all, but i only have an AURA RGB Graphics-card and not Motherboard or Case, so my testing is limited to that.

**Comment by DarthAffe** [comment]
@LokeYourLord Every help is welcome :) I've created a discord server (https://discord.gg/9kytURv) since I think it's easier to coordinate everything than here.
