### ISSUE TITLE
Todo list release

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#401]
Since it's been far too long and I keep being a bit overwhelmed by the codebase/amount of stuff to do whenever I find some time to spend on Artemis I think I'll make a todo list for the next release so I can hopefully work towards that a bit quicker

- [ ] Corsair ST100 support (probably needs a CUE.NET update, assuming the CUE SDK supports it)
- [ ] Corsair Glaive support (#387)

**Comment by DarthAffe** [comment]
Hey, just dropping some thoughts about the corsair points:
- At the moment I don't see anything that could be updated for the ST100 since there isn't a newer SDK-version. If it is supported (which could be the case) by the current SDK, I'm pretty sure it's reporting the leds like the mousepad with the Zone-Ids (but this would require some tests).

- Glaive support is a bit of a mess. The current SDK doesn't support it, but @darosultan added a workaround to CUE.NET to be able to work with it anyways (I cant say anything about the reliability of that solution since I'm not able to test it). [There is a branch for this.](https://github.com/DarthAffe/CUE.NET/tree/Glaive)

**Comment by darosultan** [comment]
Hi
Glaive support is buggy atm. The HidSharp lib doesn't always connect to the mouse properly, but once it does it's stable. I'll see if there are any updates of the library, if they don't help I'd probably have to change the HID lib to something else. I'll keep you guys updated.

**Comment by kixkid229** [comment]
Hi, I'd like to see support for SteelSeries mice in the future or even the keyboards for that matter. It would be great for the people who swear by SS gear.
