### ISSUE TITLE
11.0 Setup.exe Download does not exist

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#407]
What the title says, it is only possible to download the SourceCode.zip.

**Comment by SpoinkyNL** [comment]
I retracted that release because it was giving false positive virus
alerts/freezing. I need to address both issues (false positive I need to
fix by removing the Squirrel auto update and making my own, quite easy but
takes a bit of time) freezing issue has been hard to track down..

Op 20 nov. 2017 22:06 schreef "LokeYourLord" <notifications@github.com>:

**Comment by SpoinkyNL** [comment]
Hey, could you try the following? 
1. Download this release: https://github.com/SpoinkyNL/Artemis/releases/tag/1.10.0.0 (or run it if you ahve it already)
2. Run it once, wait a bit for the auto-update
3. Close it, run it again, it should run an intermediate version in a cmd window that'll install 1.11
4. Run Artemis from the start menu, it should be 1.11
