### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by YoFunkey** [SpoinkyNL/Artemis#415]
I've look all over if there was an IRC or anything. Was wondering if you had any interest into opening a Discord for the project! Have spent the last few days learning the program some. Might help grow the community a tad so we can all share and help each other create designs! More than happy to help out with monitoring the discord as well.
you can message me on discord if you would like "YoFunkey#3557"

**Comment by p1co** [comment]
I set this server up as a stop gap unless Robert requests it removed:

Unofficial Artemis: https://discord.gg/ncX8v9h

**Comment by HazardDev** [comment]
We could _probably_ open an official one. I don't see a reason not to.

**Comment by SpoinkyNL** [comment]
Hey, I figured I'd make one myself so that I'm owner and set it up with the new logo

https://discord.gg/S3MVaC9

**Comment by HazardDev** [comment]
@SpoinkyNL You need to make that invite permanent. It will give you a different link, but still. I have lots of experience [configuring a discord](https://discord.gg/pcmr) if you'd like me to do it for you.

**Comment by SpoinkyNL** [comment]
Yeah it's permanent I believe

Op 18 dec. 2017 08:35 schreef "Logan Saso" <notifications@github.com>:

Reopened #415 <https://github.com/SpoinkyNL/Artemis/issues/415>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/SpoinkyNL/Artemis/issues/415#event-1391553868>, or mute
the thread
