### ISSUE TITLE
DEVICE SUPPORT for CoolerMaster MasterSet ms 120

### ISSUE THREAD

**Issue by V01D0** [SpoinkyNL/Artemis#445]
Please can you add support for the CoolerMaster MasterSet ms120.

**Comment by StevenGann** [comment]
Since the title doesn't specify a make or model, I'll assume the intention is to list device support requests here.

I'd love it if ASUS Aura was supported, specifically the laptop keyboards. I'd do it myself but the Aura SDK is... unfriendly. Over my head, at least.
https://www.asus.com/campaign/aura/us/SDK.html
