### ISSUE TITLE
Logitech G810 num pad and arrows bug

### ISSUE THREAD

**Issue by IIPoliII** [SpoinkyNL/Artemis#446]
Hello,
It's seem when i do anything on my keyboard (also nothing the right down left arrow and 0 and . on num pad ae laggy and spam random colors.
Does someone a way to fix that?

Poli
Sorry for bad english

**Comment by tomrennen** [comment]
I am having the same issue as you, also on a G810. What basically happens is the right bottom of the keyboard (left, down, right arrows + numpad 0 & numpad .) are spamming between green, yellow and red on a new installation of Artemis 1.11.2.0. Its not happening with 1.11.1.0.

**Comment by Plutoss** [comment]
The problem is still there on 1.11.3
I basically stopped using Artemis because of this since it's really annoying and I'm not sure how it might affect the longevity of the light for those keys.

To add to the issue the problem with my G810 is located on the left,down,right arrow keys + 0 and . on the numpad. Even if I set a selection without them in, the right arrow and the . will flicker through RGB really fast. The right arrow is steadily flickering but the . sometimes stays lit for half a second in a single color. The left arrow key stays blue no matter what. The down arrow key sometimes doesn't lit up but if I restart Artemis it will sometimes just stay Pink. The 0 numpad key never lits up no matter what.
