### ISSUE TITLE
[Suggestion] AlienFX support based on LightFX Extender

### ISSUE THREAD

**Issue by RacerXNFS** [SpoinkyNL/Artemis#46]
Just found about this tool today, already love the concept. I've been using something called LightFX Extender for a bit now, similar idea to this app but it's more of a general trick for games that support Alienware LightFX/AlienFX. Might be cool to see both tools working in unison, or as a single app.

https://github.com/Archomeda/lightfx-extender

Here's the git, here's hoping it at least serves as an inspiration for future features.

**Comment by RacerXNFS** [comment]
Comment:  Sorry for my lack of clarity. This isn't really a device request, instead it's more of a way to support more games with Artemis by adding LightFX Extender to it. Still, if Artemis could support LightFX, thereby giving Alienware PCs and Roccat peripherals more games to use, that'd actually be pretty awesome too. Either way, it's going to be sweet seeing how this turns out.

**Comment by SpoinkyNL** [comment]
Ah I see, very interesting. Would be cool if we could support all those in an easy way. Thanks for letting me know, once we're ready for new features I'll certainly look into it.

**Comment by Archomeda** [comment]
Oh, hey there! I came across your Rocket League repo some time ago, and decided to check again today when I noticed you have moved on to this one. And when I was about to create a new issue, I saw this one. How convenient!

Anyway, I have to say, from what I've seen from this project (I have yet to test it myself), it looks really promising.
Seeing as the projects are similar, but having different features (yours supports new games and effects, while mine extends device support for existing games that use Alienware's LightFX), what do you think of merging or making both projects compatible? Currently, I have no idea how to approach that, but I'm sure we can figure something out. The ideal way that I can think of, is that my LightFX Extender captures calls and redirects them to Artemis utilizing a special API. Then Artemis can process this further.

This would mean less work for me (I don't have to fix and improve my own backend system that processes the lights, as Artemis can do that), and you don't have to look into capturing LightFX calls from supported games (as I can provide that support). Eventually, this support can be used for something like #39 as well, when a proper API has been made.

Also, since I have experience with other hardware as well, like exporting to Alienware, Corsair, Lightpack and Razer, I might be able to integrate that into Artemis too. Along with support for Guild Wars 2 since that's where my project actually started a year ago.

But for all this to work, I'm not sure if only PRs would do it. I really like the idea of this project, and I want to be involved more so I can help to include more features in this project and maybe even fully merge LightFX Extender into Artemis. If you agree, are you willing to add as a collaborator? Let me know what you think.

**Comment by SpoinkyNL** [comment]
Sounds great!

An easy way to reach out to Artemis is through the [GameStateWebserver](https://github.com/SpoinkyNL/Artemis/blob/master/Artemis/Artemis/Utilities/GameState/GameStateWebServer.cs).

We could easily modify that to handle LightFX events in a nice generic way.
Feel free to add me on [Steam](http://steamcommunity.com/profiles/76561198001930458/) so we can chat a bit further

**Comment by SpoinkyNL** [comment]
So I got back to this week and LightFX Extender seemed a bit of an overkill for what I want. So I wrote a wrapper that stores the current LightFX state and sends it as JSON to Artemis over a named pipe.

This works well and in combination with LUA I made a profile that colors all devices to whatever LightFX is receiving. 

Only thing I'm running in to now is getting games to pick up my own DLL. Placing my own LightFX.dll into the game dir works but I'd like to get a system wide solution. I tried putting the DLL in C:\Windows\System32 but Payday 2 didn't pick it up. :c

**Comment by RacerXNFS** [comment]
I don't know if there's a system-wide solution? Since then I've also been introduced to Aurora, which is pretty mental. Same concept, but it still has to manual install a DLL per game for LightFX use. If you made it system-wide, you'd probably be the first.

On Dec 21, 2016 3:26 PM, Robert Beekman <notifications@github.com> wrote:

So I got back to this week and LightFX Extender seemed a bit of an overkill for what I want. So I wrote a wrapper that stores the current LightFX state and sends it as JSON to Artemis over a named pipe.

This works well and in combination with LUA I made a profile that colors all devices to whatever LightFX is receiving.

Only thing I'm running in to now is getting games to pick up my own DLL. Placing my own LightFX.dll into the game dir works but I'd like to get a system wide solution. I tried putting the DLL in C:\Windows\System32 but Payday 2 didn't pick it up. :c
