### ISSUE TITLE
(G910) Artemis crash (FIXED)

### ISSUE THREAD

**Issue by Safritjuh** [SpoinkyNL/Artemis#84]
Hi Spoinky,

When I want to use your application for my G910, it crashes.
I have selected the Logitech RGB keyboard in the settings panel, saved it and then enabled a game-feature. 
As far as I can see, it can not find the Logitech DLL, but it is included in the packages and the G-series profile is working correctly.
It crashes upon starting a game. Afterwards I'm not able to start the application anymore and have to re-download the files (by deleting the C:\users\User...... folder)

Please find the errors attached.
[Error.txt](https://github.com/SpoinkyNL/Artemis/files/246517/Error.txt)

**Comment by SpoinkyNL** [comment]
Hi,

Please note that in order to run [Visual C++ Redistributable for Visual Studio 2012 Update 4 - 64](https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679) bit is required. Could you try installing that?

If that doesn't help, make sure Artemis is completely shut off and try updating the Logitech Gaming Software.

Let me know how it goes :)

**Comment by Safritjuh** [comment]
Hi Spoinky,

I had the package installed.
I did a repair of the package anyhow and now it is fixed.
Thanks for the quick reply and the amazing application!

Maybe something fun for Logitech G-series headset features in the future?

Keep up the good work!

**Comment by SpoinkyNL** [comment]
Great! 
Support for headsets and mice is something that is planned :)
