### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by rakers8** [SpoinkyNL/Artemis#85]
I have the Logitech Orion and can't seem to get anything working. Do you have to install it to a particular directory to get the Rocket League profile working? Do I need to have a Rocket League profile in Logitech Gaming Center? Is this made to just run in any directory (minus the Witcher mod, from what I've read)? By default it looks like all effects are enabled so I went through and disabled ALL of them except Rocket Leagues' and still can't get it to bite. Any suggestions?

I definitely recommend install instructions even if it's a portable, self-contained app. When it's not working, it allows the user to narrow down the problem. Did I miss it somewhere?

Thanks by the way, super neat. I found this by typing "logitech gaming software profile rocket league" in the goog. 
@SpoinkyNL @JewsOfHazard

**Comment by SpoinkyNL** [comment]
Hi,

I'm sorry to read that you've had such trouble getting Artemis going. Ideally it should just work right away, without requiring any sort of setup from your end, except for installing the program.

As for the regular effects, you can have one active at a time. The regular effects get overwritten by game effects as soon as you run one of the supported games. Artemis will automatically detect this, disable the effect and enable the game. 

The Witcher and CS:GO both require a bit of extra setup because Artemis needs to install some files in those games' directories. Rocket League however, should work right away.

I do agree however that some installation instructions wouldn't go amiss. I'm working hard on a giant update that'll fundamentally change the way most of the games work, so once that's done me or Hazard will make a series of video tutorials.

For now, however, could you try installing [Visual C++ Redistributable for Visual Studio 2012 Update 4 - 64 bit](https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679)? Logitech's SDK requires this, but doesn't automatically install it.

Should you still have issues after that, could you also provide me with your LGS version?

**Comment by rakers8** [comment]
No need to apologize I think it's great there's some 3rd party interest in expanding the functionality of all our expensive, backlit keyboards. 🙂 Ive looked for other sites that might have some custom profiles and apps to download and was surprised to find zero (any suggestions?) anyway, happy to help. 

Already had the C++ Redist and have the latest version of LGS (8.83.85).  Installation seemed to go fine and I selected the logi keyboard in settings. I'll try reinstalling the Redist and Artemis.

**Comment by SpoinkyNL** [comment]
I tried the current release myself and it's actually a bit broken with the latest Logitech software. Audio Visualization doesn't work well at all, and Rocket League leaves some LEDs on. But it should work nonetheless. This is already fixed in the current development release, but that's not quite done yet.

In the meanwhile can you make sure Allow games to control illumination is enabled?
http://i.imgur.com/4jEshp8.png

**Comment by SpoinkyNL** [comment]
I've uploaded a hotfix https://github.com/SpoinkyNL/Artemis/releases/tag/1.0.3.1 that fixes the Logitech issues, could you try it with that release?
